title: Milse07's Github Blog
author: Milse07
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hopefully I will finally understand how to code!
  This is like a complete foreign language to me. Not just the wording
  but the abreviations and rules of the language as well. Fingers Crossed.

# social links
twitter_username: not now
github_username:  milse07

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
